### ISSUE TITLE
【old】スマホで見ると、トップページのCode for funabashi のロゴが重なって見える

### ISSUE THREAD

**Issue by Jumpo-523** [Code-for-Funabashi/code-for-funabashi.github.io#4]

**Comment by aca-ta** [comment]
![ロゴかぶり](https://user-images.githubusercontent.com/5401476/109425167-64020080-7a2a-11eb-96c5-01216770f080.png)

**Comment by aca-ta** [comment]
タイトルロゴが背景と画像の両方に設定されていたことが原因。
背景画像の方を削除した。
